fix: add xml response for rate limit error
bnb-chain/greenfield-storage-provider pull request #1158
Opened 2023-09-20 02:41 UTC by ruojunm

### Description

fix: add xml response for rate limit error
### Rationale

Make rate limit error response format look consistent with other errors
### Example

```
curl -v 127.0.0.1:9133/auth/request_nonce
*   Trying 127.0.0.1:9133...
* Connected to 127.0.0.1 (127.0.0.1) port 9133 (#0)
> GET /auth/request_nonce HTTP/1.1
> Host: 127.0.0.1:9133
> User-Agent: curl/7.84.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 429 Too Many Requests
< Content-Type: application/xml
< Date: Wed, 20 Sep 2023 02:41:13 GMT
< Content-Length: 97
<
* Connection #0 to host 127.0.0.1 left intact
<Error><Code>960001</Code><Message>too many requests, please try it again later</Message></Error>%
```
### Changes

Notable changes: 
* add a new error code
* update error code's readme doc

2023-09-20 02:44 UTC, constwz commented on pkg/middleware/http/ratelimiter.go
> +	"github.com/bnb-chain/greenfield-storage-provider/base/types/gfsperrors"
run goimports

2023-09-20 02:52 UTC, will-2012 approved these changes

2023-09-20 02:52 UTC, will-2012 commented on base/errors.md
>  * `99`: is used for GfSp Bass App code.
Refine `Bass` to `Base`

2023-09-20 02:52 UTC, will-2012 commented on pkg/middleware/http/ratelimiter.go
> +		log.Errorw("failed to marshal error response", "error", gfspErr.String())
Refine to `"gfsp_error", gfspErr.String(), "error", err`. It is best for the log to include context and specific error reasons.

2023-09-20 02:52 UTC, will-2012 commented on pkg/middleware/http/ratelimiter.go
> +		log.Errorw("failed to write error response", "error", gfspErr.String())
Ditto.

2023-09-20 08:24 UTC, will-2012 requested changes
It is best to wait until the v0.2.6-alpha.2 version is stable before merging this PR.

2023-09-22 07:54 UTC, constwz approved these changes
LGTM

2023-09-22 08:35 UTC, annielz approved these changes

2023-09-22 08:49 UTC, BarryTong65 approved these changes

2023-09-22 08:57 UTC, will-2012 approved these changes

2023-09-22 09:08 UTC, merged